name: sundve
favicon: null
layout_spectrum: 0
typography_spectrum: 0.27524
title: Espen Sundve
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff0e0'
    - '#040812'
    - '#cfbdab'
    - '#625546'
    - '#ac9b83'
  brandStrength: 0.75
  lightness: 0.7962225889787078
  saturation: 0.5
  rhythmicContrast: 0.9830243897158653
purpose: []
